export default {
  apiServerUrl: 'http://api.cryptomania.dev',
  firstLevelSteps: [
    {
      id: 1,
      number: 1,
      level: 1,
      type: 'video',
      video_id: 'OytH5GTFlcQ',
      duration: '00:01:05',
      title: 'Что такое 2Правила?',
      comment: '<p>Привет! Если ты смотришь это видео, значит первый шаг сделан. Теперь ты с нами и получишь желаемого. Что же такое "2ПРАВИЛА"? Это секретная технология достижения быстрых и больших результатов в тех нишах которые мы тебе предложим. Это набор инструментов, знаний, основы бизнеса и много другое...</p>',
      points: 100,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 2,
      number: 2,
      level: 1,
      type: 'video',
      video_id: 'XLwnV0ip9lQ',
      duration: '00:01:46',
      title: 'Знания прежде слов и дел',
      comment: '<p>На данном шаге мы поговорим о ценностях, без которых любое начинание либо не возможно, либо не имеет смысла. Правильные и неправильные знания.</p>',
      points: 50,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 3,
      number: 3,
      level: 1,
      type: 'wallets',
      video_id: null,
      duration: null,
      title: 'Победители и неудачники. Страх',
      comment: '<p>Победители и неудачники и как не попасть в заблуждение. Страх перед действиями - вымысел.</p>',
      points: 50,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 4,
      number: 4,
      level: 1,
      type: 'video',
      video_id: 'c4TNPVR4Oxc',
      duration: '00:01:17',
      title: 'То, что нами движет всю жизнь? Задание первое',
      comment: '<p>Это то, что всю жизнь с нами, и если бы этого не было, вряд ли мы решались бы даже на маленькие подвиги и изменения. Мы ни когда бы не достигали поставленных перед собой задач и планов.</p>',
      points: 100,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 5,
      number: 5,
      level: 1,
      type: 'video',
      video_id: 'HGEcf90Ppwo',
      duration: '00:01:14',
      title: 'Результат в бизнесе = Деньги!',
      comment: '<p>В бизнесе результат - это деньги, и если то чем ты сейчас занимаешься тебе не приносит хороших денег - это ни что иное как самозанятость. Все люди знают, что время = деньги. А ты считал когда нибудь сколько стоит твой час?</p>',
      points: 50,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 6,
      number: 6,
      level: 1,
      type: 'video',
      video_id: 'jepjU2mb6Ys',
      duration: '00:01:41',
      title: 'Критерии идеальной ниши',
      comment: '<p>Важно зарабатывать деньги, иначе каким бы любимым делом ты не занимался, рано или поздно тебе придется либо оставить это дело либо смириться с плачевной ситуацией.</p>',
      points: 50,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 7,
      number: 7,
      level: 1,
      type: 'video',
      video_id: 'pwA8KwxSLBc',
      duration: '00:01:38',
      title: 'Репутация = ВСЁ!',
      comment: '<p>В бизнес квесте твоя репутация и твоя ответственность находится в трех зонах: Перед ментором, который оказал тебе высокое доверие, перед твоей командой и перед самим собой. Меняй к лучшему свою жизнь.</p>',
      points: 100,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 8,
      number: 8,
      level: 1,
      type: 'video',
      video_id: 'LX2SKfJvJFk',
      duration: '00:12:34',
      title: 'Золотая жила или идеальная ниша',
      comment: '<p>Помните как начинался кризис? Так вот, что удивительно было для меня, эту нишу он не коснулся. Более того, обороты в ней стали стремительно расти. Вопрос: "Почему многих компаний кризис подшатнул, а именно эта ниша так взлетела? Почему открывались все новые и новые рынки?". Ниша доказавшая свою надежность на деле. Вывод - доверять можно!</p>',
      points: 50,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 9,
      number: 9,
      level: 1,
      type: 'video',
      video_id: 'DDwGGQFN7mY',
      duration: '00:03:31',
      title: 'Почему у тебя всё получится?',
      comment: '<p>И сейчас покажу тебе, почему у тебя есть шанс, что все получится. Одним из самых ярких и живых примеров является...</p>',
      points: 50,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 10,
      number: 10,
      level: 1,
      type: 'video',
      video_id: 'ZLwcXjYlF3Y',
      duration: '00:00:37',
      title: 'Бесплатная регистрация',
      comment: '<p>На данном шаге тебе необходимо пройти простую и бесплатную регистрацию в системе.</p>',
      points: 50,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 11,
      number: 11,
      level: 1,
      type: 'waiting',
      video_id: 'NULL',
      duration: 'NULL',
      title: 'Получаем результат',
      comment: '<p>Ждем активации контракта.</p>',
      points: 100,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 12,
      number: 12,
      level: 1,
      type: 'video',
      video_id: 'FW-HqYg_5LI',
      duration: '00:00:51',
      title: 'Хорошие новости',
      comment: '<p>Если ты смотришь это видео значит ты прошел простую и бесплатную регистрацию, а значит эта хорошая новость специально для тебя.</p>',
      points: 50,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 13,
      number: 13,
      level: 1,
      type: 'video',
      video_id: 'jmZfYJOkQIw',
      duration: '00:02:02',
      title: 'Задание второе',
      comment: '<p>Между видео мы будем с тобой делать действия и сегодня это особо важно для тебя. Следуя строго по инструкции ты получишь свой первый результат уже через несколько минут. И это половина пути к намеченной цели.</p>',
      points: 50,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 14,
      number: 14,
      level: 1,
      type: 'waiting',
      video_id: 'NULL',
      duration: 'NULL',
      title: 'Получаем результат',
      comment: '<p>Ждем выполнения второго задания.</p>',
      points: 150,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 15,
      number: 15,
      level: 1,
      type: 'video',
      video_id: 'RNP3uHhFsWA',
      duration: '00:01:13',
      title: 'Ты в числе победителей!',
      comment: '<p>Итак, ты дошел до финиша и теперь тебе открыт доступ к секретным материалам и инструментам с помощью которых ты сможешь строить этот бизнес и зарабатывать хорошие деньги. И в этом видео я расскажу тебе почему твой успех в бизнес-квесте неизбежен.</p>',
      points: 0,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    }
  ],
  secondLevelSteps: [
    {
      id: 16,
      number: 1,
      level: 2,
      type: 'video',
      video_id: 'BsGGDJRsYuI',
      duration: '00:01:17',
      title: 'Задание третье',
      comment: '<p>Чтобы начать бизнес и получать прибыль тебе необходимо выполнить третье задание, а для этого выбери один из двух предложенных вариантов.</p>',
      points: 100,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 17,
      number: 2,
      level: 2,
      type: 'waiting',
      video_id: 'NULL',
      duration: 'NULL',
      title: 'Получаем результат',
      comment: '<p>Ждем выполнения третьего задания.</p>',
      points: 50,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 18,
      number: 3,
      level: 2,
      type: 'video',
      video_id: 'BsGGDJRsYuI1',
      duration: '00:01:00',
      title: 'Пошаговый план',
      comment: '<p>Данный шаг будет доступен после прохождения предыдущего шага</p>',
      points: 100,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 19,
      number: 4,
      level: 2,
      type: 'video',
      video_id: 'BsGGDJRsYuI2',
      duration: '00:01:37',
      title: 'Где брать клиентов и как построить команду мечты',
      comment: '<p>Данный шаг будет доступен после прохождения предыдущего шага</p>',
      points: 50,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 20,
      number: 5,
      level: 2,
      type: 'video',
      video_id: 'BsGGDJRsYuI3',
      duration: '00:01:00',
      title: 'Важные инструменты для успешной работы',
      comment: '<p>Данный шаг будет доступен после прохождения предыдущего шага</p>',
      points: 100,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 21,
      number: 6,
      level: 2,
      type: 'video',
      video_id: 'BsGGDJRsYuI4',
      duration: '00:00:51',
      title: 'Начинаем активную работу. Первая серьезная цель',
      comment: '<p>Данный шаг будет доступен после прохождения предыдущего шага</p>',
      points: 50,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 22,
      number: 7,
      level: 2,
      type: 'waiting',
      video_id: 'NULL',
      duration: 'NULL',
      title: 'Получаем результат',
      comment: '<p>Ждем достижения первой серьезной цели.</p>',
      points: 150,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 23,
      number: 8,
      level: 2,
      type: 'video',
      video_id: 'BsGGDJRsYuI5',
      duration: '00:00:52',
      title: 'Масштабирование. Вторая серьезная цель',
      comment: '<p>Данный шаг будет доступен после прохождения предыдущего шага</p>',
      points: 50,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 24,
      number: 9,
      level: 2,
      type: 'waiting',
      video_id: 'NULL',
      duration: 'NULL',
      title: 'Получаем результат',
      comment: '<p>Ждем достижения второй серьезной цели.</p>',
      points: 150,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 25,
      number: 10,
      level: 2,
      type: 'video',
      video_id: 'BsGGDJRsYuI6',
      duration: '00:00:43',
      title: 'Доступ к закрытому клубу + Приятный сюрприз!',
      comment: '<p>Данный шаг будет доступен после прохождения предыдущего шага</p>',
      points: 0,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    }
  ],
  thirdLevelSteps: [
    {
      id: 16,
      number: 1,
      level: 2,
      type: 'video',
      video_id: 'BsGGDJRsYuI',
      duration: '00:01:17',
      title: 'третий уровень открылось',
      comment: '<p>Чтобы начать бизнес и получать прибыль тебе необходимо выполнить третье задание, а для этого выбери один из двух предложенных вариантов.</p>',
      points: 100,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 17,
      number: 2,
      level: 2,
      type: 'waiting',
      video_id: 'NULL',
      duration: 'NULL',
      title: 'Получаем результат',
      comment: '<p>Ждем выполнения третьего задания.</p>',
      points: 50,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 18,
      number: 3,
      level: 2,
      type: 'video',
      video_id: 'BsGGDJRsYuI1',
      duration: '00:01:00',
      title: 'Пошаговый план',
      comment: '<p>Данный шаг будет доступен после прохождения предыдущего шага</p>',
      points: 100,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 19,
      number: 4,
      level: 2,
      type: 'video',
      video_id: 'BsGGDJRsYuI2',
      duration: '00:01:37',
      title: 'Где брать клиентов и как построить команду мечты',
      comment: '<p>Данный шаг будет доступен после прохождения предыдущего шага</p>',
      points: 50,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 20,
      number: 5,
      level: 2,
      type: 'video',
      video_id: 'BsGGDJRsYuI3',
      duration: '00:01:00',
      title: 'Важные инструменты для успешной работы',
      comment: '<p>Данный шаг будет доступен после прохождения предыдущего шага</p>',
      points: 100,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 21,
      number: 6,
      level: 2,
      type: 'video',
      video_id: 'BsGGDJRsYuI4',
      duration: '00:00:51',
      title: 'Начинаем активную работу. Первая серьезная цель',
      comment: '<p>Данный шаг будет доступен после прохождения предыдущего шага</p>',
      points: 50,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
    {
      id: 22,
      number: 7,
      level: 2,
      type: 'waiting',
      video_id: 'NULL',
      duration: 'NULL',
      title: 'Получаем результат',
      comment: '<p>Ждем достижения первой серьезной цели.</p>',
      points: 150,
      created_at: '2016-09-21 00:00:00',
      updated_at: 'NULL'
    },
  ],
  currentVideoID: null,
  currentVideoStep: null,
  isPlayerOpened: false,
  isSidebarSmall: false,
  isSidebarVisible: false,
  isMenuItemEducationOpened: false,

  isUserStepSavingProcess: false,
  isUserProfileSavingProcess: false,
  isUserAvatarSavingProcess: false,
  isUserPasswordSavingProcess: false,
  isUserPasswordResettingProcess: false,
  isAvatarSelectedToUpload: false,
  remittanceConfirmationSendingProcessInfo: {
    sendingStatus: false,
    mentorId: null
  },
  QRCodeShowingProcessInfo: {
    sendingStatus: false,
    mentorId: null
  },
  checkAllConfirmationsProcessInfo: {
    sendingStatus: false,
  },
  profileInfoForSave: null,
  currentLevel: 'first',
  serverError: false,
}
